name: lezatos
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  intl: any
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  keyboard_dismisser: ^3.0.0
  shared_preferences: ^2.5.3
  flutter_screenutil: ^5.9.3
  adaptive_theme: ^3.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
